raise Exception("Failing on purpose")
